services:
  mainservice:
    image: mainservice
    environment:
      - ENV=production
    ports:
      - 8080:8080
    # container_name: mainservice
    

  db:
    image: postgres
    expose:
      - 5432
    ports:
      - 1234:5432
    volumes:
      - "./db-volume/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=1