version: '3.8'
services:
  sepidar_db:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    ports: 
      - 1234:5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: sepidar_library
    volumes:
      - ./db-volume/:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate
    depends_on:
      - sepidar_db
    volumes:
      - ./mainservice/sql/scripts:/database
    command:
      [ "-path", "/database", "-database",  "postgres://postgres:1@sepidar_db:5432/sepidar_library?sslmode=disable", "up" ]

  sepidar:
    build: ./mainservice
    environment:
      - ENV=production
    ports:
      - 8080:8080
